### ISSUE TITLE
go-jsref.Resolver.Resolve() panics when enum has null-value

### ISSUE THREAD

**Issue by dtelyukh** [lestrrat/go-jsref#7]
My schema has such field
```
"status": {
                                "type": ["string", "null"],
                                "enum": [
                                    "sent",
                                    "duplicate",
                                    "error",
                                    "invalid",
                                    "rejected",
                                    "unqueued",
                                    "unsubscribed",
                                    null
                                ]
                            }
```

and go-jsref.Resolver.Resolve() panics

```
panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 1 [running]:
panic(0x61c800, 0xc4201333a0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
reflect.valueInterface(0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:912 +0x204
reflect.Value.Interface(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:907 +0x44
gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref.traverseExpandRefRecursive(0xc420127cb0, 0xc420127f08, 0x619640, 0xc420138f80, 0x94, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/d.telyukh/go/src/gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref/jsref.go:163 +0x205
gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref.traverseExpandRefRecursive(0xc420127cb0, 0xc420127f08, 0x619640, 0xc420138f20, 0x94, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/d.telyukh/go/src/gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref/jsref.go:183 +0x606
gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref.traverseExpandRefRecursive(0xc420127cb0, 0xc420127f08, 0x619640, 0xc420138830, 0x94, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/d.telyukh/go/src/gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref/jsref.go:183 +0x606
gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref.traverseExpandRefRecursive(0xc420127cb0, 0xc420127f08, 0x619640, 0xc4201387d0, 0x94, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/d.telyukh/go/src/gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref/jsref.go:183 +0x606
gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref.traverseExpandRefRecursive(0xc420127cb0, 0xc420127f08, 0x619640, 0xc420138780, 0x94, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/d.telyukh/go/src/gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref/jsref.go:183 +0x606
gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref.traverseExpandRefRecursive(0xc420127cb0, 0xc420127f08, 0x619640, 0xc420138700, 0x94, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/d.telyukh/go/src/gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref/jsref.go:183 +0x606
gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref.traverseExpandRefRecursive(0xc420127cb0, 0xc420127f08, 0x619640, 0xc4201386a0, 0x94, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/d.telyukh/go/src/gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref/jsref.go:183 +0x606
gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref.traverseExpandRefRecursive(0xc420127cb0, 0xc420127f08, 0x619640, 0xc420138510, 0x94, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/d.telyukh/go/src/gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref/jsref.go:183 +0x606
gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref.traverseExpandRefRecursive(0xc420127cb0, 0xc420127f08, 0x61e960, 0xc4201111a0, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/d.telyukh/go/src/gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref/jsref.go:183 +0x606
gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref.(*Resolver).Resolve(0xc420127f08, 0x61e960, 0xc4201111a0, 0x0, 0x0, 0xc420127e08, 0x1, 0x1, 0x0, 0x0, ...)
        /home/d.telyukh/go/src/gitlab.2gis.ru/mailer/mailer-docs/go-jsschema-builder/vendor/github.com/lestrrat/go-jsref/jsref.go:111 +0x37f
main.processFiles(0x662e54, 0xa, 0xc420127f08)
```

**Comment by lestrrat** [comment]
Hi, can you please provide a minimal code that reproduces this?

**Comment by dtelyukh** [comment]
go code:
```
package main

import (
...
	jsref "github.com/lestrrat/go-jsref"
	"github.com/lestrrat/go-jsref/provider"
)

var (
	srcPath, destPath, incPath string
	isVerbose                  bool
)

func main() {
...

	provider := provider.NewFS(incPath + "/")
	res := jsref.New()
	err := res.AddProvider(provider)
	if err != nil {
		log.Fatalln(err)
	}

	processFiles("/requests", res)
	processFiles("/responses", res)
}

func processFiles(dir string, res *jsref.Resolver) {
	var v interface{}

	files, err := filepath.Glob(srcPath + dir + "/*")
	if err != nil {
		log.Fatalln(err)
	}

	for _, fileName := range files {
		src, err := ioutil.ReadFile(fileName)
		if err != nil {
			log.Fatalln(err)
		}

		if err := json.Unmarshal(src, &v); err != nil {
			log.Fatalln(err)
		}

		if isVerbose {
			log.Printf("Обрабатывается схема %s\n", fileName)
		}
		result, err := res.Resolve(v, "", []jsref.Option{jsref.WithRecursiveResolution(true)}...)
		if err != nil {
			log.Fatalln(err)
		}
...
	}
}
```

schemas:
includes/status.json
```
"status": {
                                "type": ["string", "null"],
                                "enum": [
                                    "sent",
                                    "duplicate",
                                    "error",
                                    "invalid",
                                    "rejected",
                                    "unqueued",
                                    "unsubscribed",
                                    null
                                ]
                            }
```
src/emails.list.json
```
{
    "type": "object",
    "properties": {
        "meta": { "$ref": "file:///../includes/meta.json" },
        "result": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "from": {
                                "type": "string"
                            },
                            "replyTo": {
                                "type": "string"
                            },
                            "subject": {
                                "type": "string"
                            },
                            "bodyHash": {
                                "type": "string"
                            },
                            "status": { "$ref": "file:///../includes/status.json" },
                            "sentAt": {
                                "type": "string"
                            },
                            "errorText": {
                                "type": "string"
                            },
                            "createdAt": {
                                "type": "string"
                            }
                        },
                        "required": ["id", "from", "replyTo", "subject", "bodyHash", "status", "sentAt", "errorText", "createdAt"]
                    }
                }
            },
            "required": ["total", "items"]
        }
    },
    "required": ["meta", "result"]
}
```

**Comment by lestrrat** [comment]
fixed, thank you

**Comment by dtelyukh** [comment]
Thanks!
